# 网站基本信息
title: SophieS 的博客
tagline: 记录我的想法与生活
description: >- # 描述
  欢迎来到我的博客，随缘留些老鼠人生活记录
url: "https://sophiesay.github.io" # 你的网址，不要加斜杠

# 语言与时区
lang: zh-CN
timezone: Asia/Shanghai

# 社交信息（把下面的链接改成你自己的，没有就先留空）
github:
  username: SophieS
